Fatal Python error: Segmentation fault

Thread 0x00007f420b39eb38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 558 in run_once
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 527 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420b522b38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 558 in run_once
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 527 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420bb26b38 (most recent call first):
  File "/usr/local/lib/python3.9/ssl.py", line 1309 in do_handshake
  File "/usr/local/lib/python3.9/ssl.py", line 1040 in _create
  File "/usr/local/lib/python3.9/ssl.py", line 500 in wrap_socket
  File "/usr/local/lib/python3.9/http/client.py", line 1448 in connect
  File "/usr/local/lib/python3.9/http/client.py", line 974 in send
  File "/usr/local/lib/python3.9/http/client.py", line 1034 in _send_output
  File "/usr/local/lib/python3.9/http/client.py", line 1274 in endheaders
  File "/usr/local/lib/python3.9/http/client.py", line 1325 in _send_request
  File "/usr/local/lib/python3.9/http/client.py", line 1279 in request
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346 in do_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389 in https_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 494 in _call_chain
  File "/usr/local/lib/python3.9/urllib/request.py", line 534 in _open
  File "/usr/local/lib/python3.9/urllib/request.py", line 517 in open
  File "/usr/local/lib/python3.9/urllib/request.py", line 214 in urlopen
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 88 in _get_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 109 in get_device_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 268 in _poll_hosts
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 252 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420bc2ab38 (most recent call first):
  File "/usr/local/lib/python3.9/ssl.py", line 1309 in do_handshake
  File "/usr/local/lib/python3.9/ssl.py", line 1040 in _create
  File "/usr/local/lib/python3.9/ssl.py", line 500 in wrap_socket
  File "/usr/local/lib/python3.9/http/client.py", line 1448 in connect
  File "/usr/local/lib/python3.9/http/client.py", line 974 in send
  File "/usr/local/lib/python3.9/http/client.py", line 1034 in _send_output
  File "/usr/local/lib/python3.9/http/client.py", line 1274 in endheaders
  File "/usr/local/lib/python3.9/http/client.py", line 1325 in _send_request
  File "/usr/local/lib/python3.9/http/client.py", line 1279 in request
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346 in do_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389 in https_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 494 in _call_chain
  File "/usr/local/lib/python3.9/urllib/request.py", line 534 in _open
  File "/usr/local/lib/python3.9/urllib/request.py", line 517 in open
  File "/usr/local/lib/python3.9/urllib/request.py", line 214 in urlopen
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 88 in _get_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 109 in get_device_status
  File "/usr/src/homeassistant/homeassistant/components/cast/helpers.py", line 89 in fill_out_missing_chromecast_info
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 39 in discover_chromecast
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 66 in add_cast
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 195 in _add_update_service
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 120 in add_service
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 178 in on_change
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/__init__.py", line 55 in fire
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 421 in _fire_service_state_changed_event
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 538 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420cc2eb38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/xiaomi_gateway/__init__.py", line 180 in _listen_to_msg
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d0b2b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d1b6b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d2fab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d43eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d542b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d646b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d74ab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d84eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420d952b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420da56b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420db5ab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420dc5eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420dd62b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420de66b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420dfaab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e0aeb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e1b2b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e2b6b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e3bab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e4beb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e5c2b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e6c6b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e7cab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e8ceb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420e9d2b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420ead6b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420ebdab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420ed1eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420ee22b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420ef26b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f02ab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f12eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f232b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f336b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f43ab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f53eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f642b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f746b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f84ab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420f94eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420fa52b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420fb56b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420fc5ab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420fd9eb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420fea2b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f420ffa6b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42100aab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42101aeb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42102f2b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f4211336b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42114bab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f4215f3cb38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 316 in wait
  File "/usr/local/lib/python3.9/queue.py", line 180 in get
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 534 in get_events_json
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 581 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f421cfffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f421d53fb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f421ebc3b38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1167 in loop
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779 in loop_forever
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452 in _thread_main
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f422417bb38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42242bfb38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440 in result
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 636 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42256fbb38 (most recent call first):
  File "/usr/local/lib/python3.9/ssl.py", line 1309 in do_handshake
  File "/usr/local/lib/python3.9/ssl.py", line 1040 in _create
  File "/usr/local/lib/python3.9/ssl.py", line 500 in wrap_socket
  File "/usr/local/lib/python3.9/http/client.py", line 1448 in connect
  File "/usr/local/lib/python3.9/http/client.py", line 974 in send
  File "/usr/local/lib/python3.9/http/client.py", line 1034 in _send_output
  File "/usr/local/lib/python3.9/http/client.py", line 1274 in endheaders
  File "/usr/local/lib/python3.9/http/client.py", line 1325 in _send_request
  File "/usr/local/lib/python3.9/http/client.py", line 1279 in request
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346 in do_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389 in https_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 494 in _call_chain
  File "/usr/local/lib/python3.9/urllib/request.py", line 534 in _open
  File "/usr/local/lib/python3.9/urllib/request.py", line 517 in open
  File "/usr/local/lib/python3.9/urllib/request.py", line 214 in urlopen
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 88 in _get_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 109 in get_device_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/__init__.py", line 311 in __init__
  File "/usr/local/lib/python3.9/site-packages/pychromecast/__init__.py", line 86 in get_chromecast_from_cast_info
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42257ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42267ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f4226dffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42273ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f42279ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f4227fbfb38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1167 in loop
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f4228bffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007f4229131b38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Current thread 0x00007f422c5c18b0 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 215 in handle_async_request
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 281 in handle_async_request
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1699 in _send_single_request
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1655 in _send_handling_redirects
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1616 in _send_handling_auth
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1586 in send
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1494 in request
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1825 in post
  File "/usr/local/lib/python3.9/site-packages/denonavr/api.py", line 110 in async_post
  File "/usr/local/lib/python3.9/site-packages/denonavr/decorators.py", line 44 in wrapper
  File "/usr/local/lib/python3.9/site-packages/denonavr/api.py", line 162 in async_post_appcommand
  File "/usr/local/lib/python3.9/site-packages/denonavr/decorators.py", line 44 in wrapper
  File "/usr/local/lib/python3.9/site-packages/asyncstdlib/_lrucache.py", line 274 in wrapper
  File "/usr/local/lib/python3.9/site-packages/denonavr/decorators.py", line 96 in wrapper
  File "/usr/local/lib/python3.9/site-packages/denonavr/api.py", line 209 in async_get_global_appcommand
  File "/usr/local/lib/python3.9/site-packages/denonavr/foundation.py", line 246 in async_verify_avr_2016_update_method
  File "/usr/local/lib/python3.9/site-packages/denonavr/denonavr.py", line 163 in async_update
  File "/usr/src/homeassistant/homeassistant/components/denonavr/media_player.py", line 224 in async_update
  File "/usr/src/homeassistant/homeassistant/components/denonavr/media_player.py", line 173 in wrapper
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629 in run_until_complete
  File "/usr/src/homeassistant/homeassistant/runner.py", line 115 in run
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 318 in main
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 331 in <module>
  File "/usr/local/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/local/lib/python3.9/runpy.py", line 197 in _run_module_as_main
Fatal Python error: Segmentation fault

Thread 0x00007fcebeefbb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcebefffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcebff7bb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcec007fb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcec31ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcec37ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcec46b0b38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 316 in wait
  File "/usr/local/lib/python3.9/queue.py", line 180 in get
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 534 in get_events_json
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 581 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fceca0fdb38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1167 in loop
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779 in loop_forever
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452 in _thread_main
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcece511b38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcece655b38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440 in result
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 636 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fcecfb7fb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fced07ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fced0dffb38 (most recent call first):
  File "/usr/local/lib/python3.9/socket.py", line 704 in readinto
  File "/usr/local/lib/python3.9/http/client.py", line 280 in _read_status
  File "/usr/local/lib/python3.9/http/client.py", line 319 in begin
  File "/usr/local/lib/python3.9/http/client.py", line 1371 in getresponse
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440 in _make_request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699 in urlopen
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542 in request
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61 in request
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75 in get
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 93 in _request
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 171 in airplay_devices
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 274 in update
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 230 in __init__
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 193 in setup_platform
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fced17fbb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fced18ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fced292ab38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fced2a2eb38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Current thread 0x00007fced5ebe8b0 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/attr/_make.py", line 295 in attrib
  File "/usr/local/lib/python3.9/site-packages/denonavr/foundation.py", line 40 in DenonAVRDeviceInfo
  File "/usr/local/lib/python3.9/site-packages/denonavr/foundation.py", line 37 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/usr/local/lib/python3.9/site-packages/denonavr/denonavr.py", line 19 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/usr/local/lib/python3.9/site-packages/denonavr/__init__.py", line 14 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 972 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/usr/src/homeassistant/homeassistant/components/denonavr/__init__.py", line 4 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1030 in _gcd_import
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127 in import_module
  File "/usr/src/homeassistant/homeassistant/loader.py", line 524 in get_component
  File "/usr/src/homeassistant/homeassistant/setup.py", line 206 in _async_setup_component
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629 in run_until_complete
  File "/usr/src/homeassistant/homeassistant/runner.py", line 115 in run
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 318 in main
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 331 in <module>
  File "/usr/local/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/local/lib/python3.9/runpy.py", line 197 in _run_module_as_main
Fatal Python error: Segmentation fault

Thread 0x00007fc90fc0db38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 558 in run_once
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 527 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc90ff91b38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 558 in run_once
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 527 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc910a95b38 (most recent call first):
  File "/usr/local/lib/python3.9/ssl.py", line 1309 in do_handshake
  File "/usr/local/lib/python3.9/ssl.py", line 1040 in _create
  File "/usr/local/lib/python3.9/ssl.py", line 500 in wrap_socket
  File "/usr/local/lib/python3.9/http/client.py", line 1448 in connect
  File "/usr/local/lib/python3.9/http/client.py", line 974 in send
  File "/usr/local/lib/python3.9/http/client.py", line 1034 in _send_output
  File "/usr/local/lib/python3.9/http/client.py", line 1274 in endheaders
  File "/usr/local/lib/python3.9/http/client.py", line 1325 in _send_request
  File "/usr/local/lib/python3.9/http/client.py", line 1279 in request
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346 in do_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389 in https_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 494 in _call_chain
  File "/usr/local/lib/python3.9/urllib/request.py", line 534 in _open
  File "/usr/local/lib/python3.9/urllib/request.py", line 517 in open
  File "/usr/local/lib/python3.9/urllib/request.py", line 214 in urlopen
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 88 in _get_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 109 in get_device_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 268 in _poll_hosts
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 252 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc910b99b38 (most recent call first):
  File "/usr/local/lib/python3.9/ssl.py", line 1309 in do_handshake
  File "/usr/local/lib/python3.9/ssl.py", line 1040 in _create
  File "/usr/local/lib/python3.9/ssl.py", line 500 in wrap_socket
  File "/usr/local/lib/python3.9/http/client.py", line 1448 in connect
  File "/usr/local/lib/python3.9/http/client.py", line 974 in send
  File "/usr/local/lib/python3.9/http/client.py", line 1034 in _send_output
  File "/usr/local/lib/python3.9/http/client.py", line 1274 in endheaders
  File "/usr/local/lib/python3.9/http/client.py", line 1325 in _send_request
  File "/usr/local/lib/python3.9/http/client.py", line 1279 in request
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346 in do_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389 in https_open
  File "/usr/local/lib/python3.9/urllib/request.py", line 494 in _call_chain
  File "/usr/local/lib/python3.9/urllib/request.py", line 534 in _open
  File "/usr/local/lib/python3.9/urllib/request.py", line 517 in open
  File "/usr/local/lib/python3.9/urllib/request.py", line 214 in urlopen
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 88 in _get_status
  File "/usr/local/lib/python3.9/site-packages/pychromecast/dial.py", line 109 in get_device_status
  File "/usr/src/homeassistant/homeassistant/components/cast/helpers.py", line 89 in fill_out_missing_chromecast_info
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 39 in discover_chromecast
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 66 in add_cast
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 195 in _add_update_service
  File "/usr/local/lib/python3.9/site-packages/pychromecast/discovery.py", line 120 in add_service
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 178 in on_change
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/__init__.py", line 55 in fire
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 421 in _fire_service_state_changed_event
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 538 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc911f5db38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912121b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912265b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912369b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc91246db38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912571b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912675b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912779b38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440 in result
  File "/usr/src/homeassistant/homeassistant/core.py", line 1147 in set
  File "/config/custom_components/icloud3/device_tracker.py", line 4527 in _set_state
  File "/config/custom_components/icloud3/device_tracker.py", line 5603 in _update_device_sensors_hass
  File "/config/custom_components/icloud3/device_tracker.py", line 5537 in _update_device_sensors
  File "/config/custom_components/icloud3/device_tracker.py", line 2893 in _update_device_icloud
  File "/config/custom_components/icloud3/device_tracker.py", line 2006 in _polling_loop_5_sec_device
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc91287db38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912981b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912a85b38 (most recent call first):
  File "/usr/local/lib/python3.9/selectors.py", line 416 in select
  File "/usr/local/lib/python3.9/subprocess.py", line 1979 in _communicate
  File "/usr/local/lib/python3.9/subprocess.py", line 1134 in communicate
  File "/usr/local/lib/python3.9/subprocess.py", line 507 in run
  File "/usr/local/lib/python3.9/subprocess.py", line 424 in check_output
  File "/usr/src/homeassistant/homeassistant/components/command_line/__init__.py", line 36 in check_output_or_log
  File "/usr/src/homeassistant/homeassistant/components/command_line/switch.py", line 116 in _query_state_value
  File "/usr/src/homeassistant/homeassistant/components/command_line/switch.py", line 148 in _query_state
  File "/usr/src/homeassistant/homeassistant/components/command_line/switch.py", line 154 in update
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912b89b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912c8db38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912d91b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912e95b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc912fd9b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9130ddb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9131e1b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9132e5b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9133e9b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9134edb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9135f1b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9136f5b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9137f9b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9138fdb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc913a01b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc913b05b38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86 in create_connection
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174 in _new_conn
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205 in connect
  File "/usr/local/lib/python3.9/http/client.py", line 974 in send
  File "/usr/local/lib/python3.9/http/client.py", line 1034 in _send_output
  File "/usr/local/lib/python3.9/http/client.py", line 1274 in endheaders
  File "/usr/local/lib/python3.9/http/client.py", line 1325 in _send_request
  File "/usr/local/lib/python3.9/http/client.py", line 1279 in request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239 in request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394 in _make_request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699 in urlopen
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542 in request
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61 in request
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75 in get
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 93 in _request
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 171 in airplay_devices
  File "/usr/src/homeassistant/homeassistant/components/itunes/media_player.py", line 274 in update
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc913c09b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc913d0db38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc913e11b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc913f15b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc914059b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc91419db38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9142a1b38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86 in create_connection
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174 in _new_conn
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205 in connect
  File "/usr/local/lib/python3.9/http/client.py", line 974 in send
  File "/usr/local/lib/python3.9/http/client.py", line 1034 in _send_output
  File "/usr/local/lib/python3.9/http/client.py", line 1274 in endheaders
  File "/usr/local/lib/python3.9/http/client.py", line 1325 in _send_request
  File "/usr/local/lib/python3.9/http/client.py", line 1279 in request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239 in request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394 in _make_request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699 in urlopen
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542 in request
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590 in post
  File "/usr/local/lib/python3.9/site-packages/bravia_tv/braviarc.py", line 123 in bravia_req_json
  File "/usr/local/lib/python3.9/site-packages/bravia_tv/braviarc.py", line 198 in get_power_status
  File "/usr/src/homeassistant/homeassistant/components/braviatv/__init__.py", line 173 in _update_tv_data
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9143a5b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9144a9b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9145adb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9146b1b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9147b5b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9148f9b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9149fdb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc914b01b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc914c05b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc914d49b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc914e8db38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/xiaomi_gateway/__init__.py", line 180 in _listen_to_msg
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc915cd1b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc915e15b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc915f19b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc918dffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9193d2b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9194d6b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc91e8ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc920d3fb38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1167 in loop
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779 in loop_forever
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452 in _thread_main
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc921566b38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 316 in wait
  File "/usr/local/lib/python3.9/queue.py", line 180 in get
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 534 in get_events_json
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 581 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9283ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9289fbb38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440 in result
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 636 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc9299ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92a9ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92afffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92b5ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92bbffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92c5fbb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92c6ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92d712b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc92d816b38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Current thread 0x00007fc930ca68b0 (most recent call first):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 463 in async_added_to_hass
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 282 in async_added_to_hass
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 208 in async_added_to_hass
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 587 in async_added_to_hass
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681 in add_to_platform_finish
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587 in _async_add_entity
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629 in run_until_complete
  File "/usr/src/homeassistant/homeassistant/runner.py", line 115 in run
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 318 in main
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 331 in <module>
  File "/usr/local/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/local/lib/python3.9/runpy.py", line 197 in _run_module_as_main
Fatal Python error: Segmentation fault

Thread 0x00007fd8071f4b38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/lib/python3.9/queue.py", line 171 in get
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 534 in get_events_json
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 581 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd80f9ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd810018b38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd8123bfb38 (most recent call first):
  File "/usr/local/lib/python3.9/selectors.py", line 416 in select
  File "/usr/local/lib/python3.9/subprocess.py", line 1979 in _communicate
  File "/usr/local/lib/python3.9/subprocess.py", line 1134 in communicate
  File "/usr/local/lib/python3.9/subprocess.py", line 507 in run
  File "/usr/local/lib/python3.9/subprocess.py", line 424 in check_output
  File "/usr/src/homeassistant/homeassistant/components/command_line/__init__.py", line 36 in check_output_or_log
  File "/usr/src/homeassistant/homeassistant/components/command_line/switch.py", line 116 in _query_state_value
  File "/usr/src/homeassistant/homeassistant/components/command_line/switch.py", line 148 in _query_state
  File "/usr/src/homeassistant/homeassistant/components/command_line/switch.py", line 154 in update
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd812a2ab38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1167 in loop
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779 in loop_forever
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452 in _thread_main
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd816111b38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd816255b38 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440 in result
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 636 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd81777fb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd8183ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd8189ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86 in create_connection
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174 in _new_conn
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358 in connect
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010 in _validate_conn
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382 in _make_request
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699 in urlopen
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655 in send
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542 in request
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555 in get
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 146 in thinq2_get
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 481 in get2
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 494 in get_devices
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 685 in _load_devices
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 733 in refresh_devices
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1106 in _get_device_snapshot
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1155 in device_poll
  File "/config/custom_components/smartthinq_sensors/wideq/washerDryer.py", line 232 in poll
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 477 in _device_update
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277 in wrapper
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd8193fbb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd8194ffb38 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd81a53bb38 (most recent call first):
  File "/usr/local/lib/python3.9/selectors.py", line 416 in select
  File "/usr/local/lib/python3.9/subprocess.py", line 1979 in _communicate
  File "/usr/local/lib/python3.9/subprocess.py", line 1134 in communicate
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 97 in install_package
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 193 in _install
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fd81a63fb38 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Current thread 0x00007fd81dacf8b0 (most recent call first):
  File "/usr/local/lib/python3.9/json/decoder.py", line 338 in decode
  File "/usr/local/lib/python3.9/json/__init__.py", line 346 in loads
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 198 in _load
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 146 in decode_complete
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 90 in decode_complete
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 119 in decode
  File "/usr/src/homeassistant/homeassistant/auth/__init__.py", line 525 in async_validate_access_token
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 72 in async_validate_auth_header
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 119 in auth_middleware
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78 in ban_middleware
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24 in request_context_middleware
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98 in forwarded_middleware
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60 in security_filter_middleware
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119 in impl
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499 in _handle
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422 in _handle_request
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629 in run_until_complete
  File "/usr/src/homeassistant/homeassistant/runner.py", line 115 in run
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 318 in main
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 331 in <module>
  File "/usr/local/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/local/lib/python3.9/runpy.py", line 197 in _run_module_as_main
